projecttodo/urls.py
#from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('todolist.urls'))
]

todolist/urls.py
from todolist.views import addToDo
from django.urls import path

from . import views

app_name = 'todolist'
urlpatterns = [
    # ex: /todolist/
    path('', views.index, name='index'),
    # ex: /todolist/add/
    path('add/', views.addToDo, name='addtodo'),
    # ex: /todolist/1/change
    path('<int:todo_id>/change/', views.changeParticipate, name='changetodo'),
    # ex: /todolist/1/update
    path('<int:todo_id>/update/', views.updateToDo, name='updatetodo'),
    # ex: /todolist/1/delete
    path('<int:todo_id>/delete/', views.deleteToDo, name='deletetodo'),
]

todolist/models.py
from django.db import models
from django.db.models.fields import BooleanField
from django.utils import timezone

# Create your models here.
class ToDo(models.Model):
    event_name = models.CharField(max_length=100)
    description = models.TextField(max_length=300)
    start_date = models.DateTimeField('event start')
    create_date = models.DateTimeField('create date', auto_now=True)
    participate = models.BooleanField('participated?', default=False)
    def __str__(self):
        return self.event_name

todolist/forms.py
from todolist.validateAlgorithm import validate_check_boolean
from django.forms import widgets
from .models import ToDo
from django import forms

class ToDoForm(forms.ModelForm):
    class Meta:
        model = ToDo
        fields = ('event_name','description','start_date')
        widgets = {
            'event_name': forms.TextInput(attrs={'class':'form-control'}),
            'description': forms.Textarea(attrs={'class':'form-control'}),
            'start_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

todolist/views.py
from datetime import date
from django.db.models.query import QuerySet
from django.http import HttpResponseRedirect
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib import messages
from .models import ToDo
from .forms import ToDoForm

# Create your views here.
def index(request):
    """
    Return Homepage
    """
    template_name = 'todolist/index.html'
    todolist = ToDo.objects.filter().order_by('start_date')
    todo_dict = {}
    for item in todolist:
        date_key = timezone.localtime(item.start_date).date()
        todo_dict.setdefault(date_key, []).append(item)
    form = ToDoForm()
    context = {
        'todolist': todo_dict,
        'form': form,
        }
    return render(request, template_name, context)


def addToDo(request):
    if request.method == 'POST':
        form = ToDoForm(request.POST)
        form.full_clean()
        event_name = form.data['event_name']
        description = form.data['description']
        start_date = form.data['start_date']
        
        todo = ToDo(event_name=event_name, description=description, start_date=start_date)
        todo.save()
        messages.success(request, 'To-Do form successfully added!')
        return HttpResponseRedirect(reverse('todolist:index'))
        
        
    else:
        messages.warning(request, 'Error adding To-Do event')
        return HttpResponseRedirect(reverse('todolist:index'))

def changeParticipate(request, todo_id):
    if request.method == 'POST':
        todo = get_object_or_404(ToDo, pk=todo_id)
        todo.participate = not todo.participate
        todo.save()
        messages.success(request, 'Participate changed to ' + str(todo.participate))
        return HttpResponseRedirect(reverse('todolist:index'))
    else:
        messages.warning(request, 'Error changing the participate')
        return HttpResponseRedirect(reverse('todolist:index'))

def updateToDo(request, todo_id):
    old_todo = get_object_or_404(ToDo, pk=todo_id)
    old_todo.start_date = timezone.localtime(old_todo.start_date).strftime("%Y-%m-%dT%H:%M:%S")
    template_name = 'todolist/update.html'
    if request.method == 'GET':
        form = ToDoForm(instance=old_todo)
        context = {
            'name': old_todo.event_name,
            'id': old_todo.pk,
            'form': form,
            }
        return render(request, template_name, context)
    else:
        form = ToDoForm(request.POST)
        form.full_clean()
        old_todo.event_name = form.data['event_name']
        old_todo.description = form.data['description']
        old_todo.start_date = form.data['start_date']
        old_todo.save()
        messages.success(request, 'To-Do form successfully saved!')
        return HttpResponseRedirect(request.path_info)

def deleteToDo(request, todo_id):
    if request.method == 'POST':
        todo = get_object_or_404(ToDo, pk=todo_id)
        todo.delete()
        messages.success(request, 'successfully deleted!')
        return HttpResponseRedirect(reverse('todolist:index'))
    else:
        messages.warning(request, 'Error deleting To-Do event')
        return HttpResponseRedirect(reverse('todolist:index'))

todolist/templates/todolist/alert.html
{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="row justify-content-center" role="alert">
                <div  {% if message.tags %} class="btn btn-{{ message.tags }} " {% endif %}> {{ message }} </div>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}

todolist/templates/todolist/base.html
{% block content %}
    {% block top %}
        <!DOCTYPE html>
        <html>
            <head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
                <title>To Do List</title>
                {% load static %}
                <link rel="stylesheet" type="text/css" href="{% static 'todolist/css/style.css' %}">
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
                <script src="https://kit.fontawesome.com/ba8c526c07.js" crossorigin="anonymous"></script>
                <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
                <script src="https://unpkg.com/@popperjs/core@2"></script>
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
            </head>
            <body>
                <!-- content -->
    {% endblock %}

    {% block bot %}
                <!-- content -->
            </body>
        </html>
    {% endblock %}
{% endblock %}

todolist/templates/todolist/index.html
{% extends "./base.html" %}
{% block top %}
    {{ block.super }}
    <div class="container-fluid ">
        {% if messages %}
            {% for message in messages %}
            <div class="row justify-content-center">
                <div class="col col-md-8 alert alert-warning alert-dismissible fade show" role="alert">
                    <div  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </div>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
            {% endfor %}
        {% endif %}
        <div class="row justify-content-center">
            <div class="col col-md-8">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">To-Do-List</h4>
                        <p class="card-text">Upcoming event and To-do-list that you can interact with.</p>
                    </div>
                    <hr/>
                    <div class="row justify-content-center">
                        <div class="col col-lg-4">
                            <button type="button" class="btn btn-primary btn-lg" style="width: 100%;" data-toggle="modal" data-target="#modelId">
                                Add new To Do
                            </button>
                        </div>
                    </div>
                    <br/>
                    <div class="list-group list-group-flush" id="myGroup">
                        {% if todolist %}
                            
                            {% for date, item_list in todolist.items %}
                                {% now "Y-m-d" as todays_date %}
                                <a class="btn {% if date|date:'Y-m-d' == todays_date %} btn-success active {% else %} btn-light {% endif %} list-group-item"
                                    data-toggle="collapse" data-parent="#myGroup" href="#content{{ forloop.counter }}" aria-pressed="true"
                                    aria-expanded="false" aria-controls="content{{ forloop.counter }}">
                                    {{ date }} {% if date|date:'Y-m-d' < todays_date %} (Old) {% endif %}
                                </a>
                                <div class="collapse {% if date|date:'Y-m-d' == todays_date %} show {% endif %}" id="content{{ forloop.counter }}">
                                    <div class="list-group-item d-none d-lg-block">
                                        <div class="row">
                                            <div class="col-lg-2">
                                                Event name
                                            </div>
                                            <div class="col-lg-4">
                                                Description
                                            </div>
                                            <div class="col-lg-3">
                                                Event start
                                            </div>
                                            <div class="col-lg-2">
                                                Check
                                            </div>
                                            <div class="col-lg-1">
                                                Del
                                            </div>
                                        </div>
                                    </div>
                                    {% for item in item_list %}
                                    <div class="list-group-item">
                                        <a href="{% url 'todolist:updatetodo' item.pk %}" class="row clickable btn-light" style="text-decoration: none; color: black;">
                                            <div class="col-lg-2 my-auto">
                                                <div style="display: block;
                                                            display: -webkit-box;
                                                            margin: 0 auto;
                                                            line-height: 1.3;
                                                            -webkit-line-clamp: 2;
                                                            -webkit-box-orient: vertical;
                                                            overflow: hidden;
                                                            text-overflow: ellipsis;">
                                                    {{ item.event_name }}
                                                </div>
                                            </div>
                                            <div class="col-lg-4 my-auto">
                                                <div style="display: block;
                                                            display: -webkit-box;
                                                            margin: 0 auto;
                                                            line-height: 1.2;
                                                            -webkit-line-clamp: 2;
                                                            -webkit-box-orient: vertical;
                                                            overflow: hidden;
                                                            text-overflow: ellipsis;">
                                                    {{ item.description }}
                                                </div>
                                                
                                            </div>
                                            <div class="col-lg-3 my-auto">
                                                {{ item.start_date|date:'P' }} {# H is  hour, i is minute, P is time with am/pm #}
                                            </div>
                                            <div class="col-lg-2">
                                                <form action="{% url 'todolist:changetodo' item.pk %}" method="POST">
                                                    {% csrf_token %}
                                                        {% if item.participate %}
                                                            <button type="submit" class="btn">
                                                                <i class="fas fa-check"></i>
                                                            </button>
                                                        {% else %}
                                                            <button type="submit" class="btn">
                                                                <i class="fas fa-times"></i>
                                                            </button>
                                                        {% endif %}
                                                </form>
                                            </div>
                                            <div class="col-lg-1">
                                                <form action="{% url 'todolist:deletetodo' item.pk %}" method="POST">
                                                    {% csrf_token %}
                                                    <button type="submit" class="btn btn-danger">
                                                        <i class="fas fa-times"></i>
                                                    </button>
                                                </form>
                                            </div>
                                        </a>
                                    </div>
                                    {% endfor %}
                                </div>
                            {% endfor %}
                        {% else %}
                            <p class="list-group-item text-center">There is nothing here.</p>
                        {% endif %}
                        
                    </div>
                </div>
            </div>
            
        </div>

        <!-- Modal -->
        <div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Add To-Do Event</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                    </div>
                    <form action="{% url 'todolist:addtodo' %}" class="form-group" method = "post">
                        <div class="modal-body">
                            {% csrf_token %}
                            {{form.as_p}}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <input type="submit" class="btn btn-primary" value = "Add">
                        </div>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block bot %}

    {{ block.super }}
{% endblock %}

todolist/templates/todolist/results.html
{% extends "./base.html" %}
{% block top %}
    {{ block.super }}
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}

{% block bot %}

    {{ block.super }}
{% endblock %}

    

todolist/templates/todolist/update.html
{% extends "./base.html" %}
{% block top %}
    {{ block.super }}
    {% if messages %}
        {% for message in messages %}
        <div class="row justify-content-center">
            <div class="col col-md-6 alert alert-warning alert-dismissible fade show" role="alert">
                <div  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </div>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        {% endfor %}
    {% endif %}
    <div class="row justify-content-center">
        <div class="col col-md-6">
            <div class="card text-left">
                <div class="card-body">
                  <h4 class="card-title">Event name: {{ name }}</h4>
                  <p class="card-text">ID: {{ id }}</p>
                  <form action="{% url 'todolist:updatetodo' id%}" class="form-group" method = "post">
                      {% csrf_token %}
                      {{form.as_p}}
                      <a href="{% url 'todolist:index' %}" class="btn btn-secondary">Home</a>
                      <input type="submit" class="btn btn-primary" value = "Save">
                  </form>
                </div>
            </div>
        </div>
    </div>
    
    
{% endblock %}

{% block bot %}

    {{ block.super }}
{% endblock %}